# Generated by Django 4.2 on 2024-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('ocupacion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
