# Generated by Django 4.2 on 2024-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion_alter_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='num_socio',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
